@url=http://localhost:3000/api/v1/


### Test requests to the /cat API
GET {{url}}cats

###

GET {{url}}cats/03d5b4135bbe6ecda79a

###

DELETE {{url}}cats/2f2fef667b7553ade5b4

###

PUT {{url}}cats/
content-type: application/json

{
    "name": "Alvar",
    "breed": "Sphynx",
    "favouriteFood": "Tuna steak",
    "accepsBellyRubs": true,
    "age": 5,
    "image": "",
    "description": "Cuddly little goblin",
    "adopted": false,
    "id": "2f2fef667b7553ade5b4"
}
###
# Add a cat to the DB
POST {{url}}cats/
content-type: application/json

{
    "name": "Alvar",
    "breed": "Sphynx",
    "favouriteFood": "Tuna Qsteak",
    "accepsBellyRubs": true,
    "age": 5,
    "image": "",
    "description": "Cuddly little goblin",
    "adopted": false
}
###
# Erronous post, will fail validation
POST {{url}}cats/
content-type: application/json

{
    "name": "Alvar",
    "favouriteFood": "Tuna",
    "accepsBellyRubs": true
}

###
# get all adopted cats
GET  {{url}}cats/adopt/adopted

###
# get all non adopted cats
GET  {{url}}cats/adopt/notadopted

###
# Adopt a cat!
PATCH   {{url}}cats/adopt/03d5b4135bbe6ecda79a